services:
  mysql:
    image: 'mysql:8'
    environment:
      - 'MYSQL_DATABASE=basicsSpringdb'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_USER=basicsSpring'
    ports:
      - '3306:3306'
